// Demo data for PrepIQ - pre-loaded for hackathon judges

export const DEMO_USER = {
  id: "usr_xyz123",
  name: "John Doe",
  email: "john.doe@example.com",
  college: "XYZ University",
  branch: "Computer Science",
  year: "3rd Year",
  city: "New Delhi",
  career_goal: "Software Engineer",
  target_company_type: "MNC",
  placement_timeline: "6 months",
  avatar: null,
  streak: 12,
  created_at: "2025-11-01",
};

export const DEMO_SESSIONS = [
  {
    id: "s1",
    date: "2026-04-28",
    domain: "Technical",
    difficulty: "Intermediate",
    duration_secs: 1200,
    overall_score: 72,
    content_score: 75,
    communication_score: 70,
    confidence_score: 68,
    relevance_score: 78,
    body_language_score: 69,
    topic: "Data Structures & Algorithms",
  },
  {
    id: "s2",
    date: "2026-04-30",
    domain: "HR",
    difficulty: "Beginner",
    duration_secs: 900,
    overall_score: 65,
    content_score: 62,
    communication_score: 72,
    confidence_score: 60,
    relevance_score: 68,
    body_language_score: 63,
    topic: "Behavioural Questions",
  },
  {
    id: "s3",
    date: "2026-05-01",
    domain: "Technical",
    difficulty: "Beginner",
    duration_secs: 1500,
    overall_score: 78,
    content_score: 82,
    communication_score: 74,
    confidence_score: 76,
    relevance_score: 80,
    body_language_score: 78,
    topic: "System Design Basics",
  },
  {
    id: "s4",
    date: "2026-05-02",
    domain: "Technical",
    difficulty: "Intermediate",
    duration_secs: 1100,
    overall_score: 81,
    content_score: 85,
    communication_score: 78,
    confidence_score: 80,
    relevance_score: 82,
    body_language_score: 80,
    topic: "Arrays & Strings",
  },
  {
    id: "s5",
    date: "2026-05-03",
    domain: "HR",
    difficulty: "Intermediate",
    duration_secs: 800,
    overall_score: 74,
    content_score: 70,
    communication_score: 80,
    confidence_score: 72,
    relevance_score: 75,
    body_language_score: 71,
    topic: "Tell Me About Yourself",
  },
  {
    id: "s6",
    date: "2026-05-04",
    domain: "Technical",
    difficulty: "Advanced",
    duration_secs: 1800,
    overall_score: 85,
    content_score: 88,
    communication_score: 82,
    confidence_score: 84,
    relevance_score: 86,
    body_language_score: 83,
    topic: "Dynamic Programming",
  },
];

export const DEMO_ROADMAP = [
  {
    phase: 1,
    title: "Foundation",
    timeframe: "Month 1-2",
    status: "in_progress" as const,
    progress: 60,
    milestones: [
      { id: "m1", text: "Complete DSA basics (Arrays, Strings, Recursion)", completed: true },
      { id: "m2", text: "Learn Python deeply — OOP, collections, decorators", completed: true },
      { id: "m3", text: "Solve 50 LeetCode Easy problems", completed: true },
      { id: "m4", text: "Complete 2 mock interviews (HR round)", completed: false },
      { id: "m5", text: "Build personal portfolio project", completed: false },
    ],
  },
  {
    phase: 2,
    title: "Building",
    timeframe: "Month 2-4",
    status: "locked" as const,
    progress: 0,
    milestones: [
      { id: "m6", text: "System Design basics (HLD, LLD, Databases)", completed: false },
      { id: "m7", text: "Solve 80 LeetCode Medium problems", completed: false },
      { id: "m8", text: "Build 2 projects with GitHub", completed: false },
      { id: "m9", text: "Complete 4 technical mock interviews", completed: false },
      { id: "m10", text: "Learn REST APIs & backend basics", completed: false },
    ],
  },
  {
    phase: 3,
    title: "Interview Ready",
    timeframe: "Month 4-5",
    status: "locked" as const,
    progress: 0,
    milestones: [
      { id: "m11", text: "Full mock interview simulation (Technical + HR)", completed: false },
      { id: "m12", text: "Apply to 20 companies", completed: false },
      { id: "m13", text: "Practice behavioural questions (STAR method)", completed: false },
      { id: "m14", text: "Certificate validation complete", completed: false },
      { id: "m15", text: "Get peer feedback on 3 mock sessions", completed: false },
    ],
  },
  {
    phase: 4,
    title: "Placement Sprint",
    timeframe: "Month 5-6",
    status: "locked" as const,
    progress: 0,
    milestones: [
      { id: "m16", text: "Daily mock interview practice", completed: false },
      { id: "m17", text: "Resume finalised and validated", completed: false },
      { id: "m18", text: "Internship applications sent", completed: false },
      { id: "m19", text: "Target: 3+ interview calls received", completed: false },
      { id: "m20", text: "Negotiate offers & accept placement", completed: false },
    ],
  },
];

export const DEMO_SKILLS = {
  current: ["Python", "JavaScript", "React", "HTML/CSS", "Git", "SQL", "Data Structures"],
  required: ["System Design", "Docker", "AWS", "CI/CD", "TypeScript", "Testing", "Algorithms", "REST APIs", "GraphQL", "Microservices"],
  gap: ["System Design", "Docker", "AWS", "CI/CD", "TypeScript", "Testing"],
};

export const DEMO_CERTIFICATES = [
  {
    id: "c1",
    name: "Python for Data Science",
    issuer: "Coursera",
    date: "2025-08-15",
    is_valid: true,
    score: "94%",
  },
  {
    id: "c2",
    name: "Web Development Bootcamp",
    issuer: "Udemy",
    date: "2025-10-22",
    is_valid: true,
    score: "Completed",
  },
  {
    id: "c3",
    name: "AWS Cloud Practitioner",
    issuer: "Amazon",
    date: "2026-01-10",
    is_valid: false,
    flag_reason: "Font inconsistency on issuer name",
    score: "Pass",
  },
];

export const DEMO_CHAT_HISTORY = [
  { role: "user" as const, message: "What skills do I need for a Software Engineer role at an MNC?", timestamp: "10:30 AM" },
  { role: "assistant" as const, message: "Great question, Adarsh! For a Software Engineer role at an MNC, you'll need:\n\n**Core Skills:**\n• Data Structures & Algorithms (your current focus!)\n• System Design (HLD & LLD)\n• One strong programming language (Python ✅)\n\n**Good to Have:**\n• Cloud basics (AWS/GCP)\n• Docker & CI/CD\n• Testing frameworks\n\nBased on your roadmap, you're on track with Phase 1. Keep solving LeetCode problems and you'll be ready for Phase 2 soon! 🚀", timestamp: "10:31 AM" },
  { role: "user" as const, message: "How should I prepare for 'Tell me about yourself'?", timestamp: "10:45 AM" },
  { role: "assistant" as const, message: "Here's a proven framework for 'Tell me about yourself':\n\n**The Present-Past-Future Formula:**\n\n1️⃣ **Present**: \"I'm a 3rd year CS student at XYZ University, currently focused on full-stack development and DSA.\"\n\n2️⃣ **Past**: \"I've built projects using React and Python, and completed certifications in Data Science and Web Development.\"\n\n3️⃣ **Future**: \"I'm targeting a Software Engineer role at an MNC, and I'm using PrepIQ to systematically prepare for technical and behavioural interviews.\"\n\n**Pro tips:**\n• Keep it under 90 seconds\n• Show enthusiasm, not just facts\n• Connect your story to the role\n\nWant me to give you a practice question to try?", timestamp: "10:46 AM" },
  { role: "user" as const, message: "Yes, give me a practice question!", timestamp: "10:48 AM" },
  { role: "assistant" as const, message: "Here's your practice question:\n\n💡 **\"Walk me through a challenging project you've worked on. What was your role, what obstacles did you face, and what did you learn?\"**\n\nUse the **STAR method**:\n• **S**ituation — Set the context\n• **T**ask — Your responsibility\n• **A**ction — What you did\n• **R**esult — The outcome + learning\n\nTake your time and type your answer. I'll give you feedback! 🎯", timestamp: "10:48 AM" },
];

export const DEMO_INTERNSHIPS = [
  {
    id: "i1",
    title: "Software Development Intern",
    company: "Microsoft",
    domain: "Software Engineering",
    skills_required: ["Python", "JavaScript", "React", "System Design"],
    stipend: "₹80,000/month",
    location: "Bangalore",
    work_mode: "Hybrid",
    match_score: 87,
    apply_url: "https://careers.microsoft.com/",
    match_reason: "Strong alignment with your Python and React skills, and your SWE career goal.",
  },
  {
    id: "i2",
    title: "Backend Engineer Intern",
    company: "Flipkart",
    domain: "Software Engineering",
    skills_required: ["Python", "SQL", "REST APIs", "Data Structures"],
    stipend: "₹60,000/month",
    location: "Bangalore",
    work_mode: "Office",
    match_score: 82,
    apply_url: "https://www.flipkartcareers.com/",
    match_reason: "Your DSA progress and Python expertise make you a strong candidate.",
  },
  {
    id: "i3",
    title: "Full Stack Developer Intern",
    company: "Razorpay",
    domain: "Software Engineering",
    skills_required: ["JavaScript", "React", "Node.js", "SQL"],
    stipend: "₹50,000/month",
    location: "Remote",
    work_mode: "Remote",
    match_score: 79,
    apply_url: "https://razorpay.com/jobs/",
    match_reason: "Your React skills match well. Building Node.js skills will boost this match.",
  },
  {
    id: "i4",
    title: "SDE Intern",
    company: "Google",
    domain: "Software Engineering",
    skills_required: ["Python", "Algorithms", "System Design", "Testing"],
    stipend: "₹1,20,000/month",
    location: "Hyderabad",
    work_mode: "Office",
    match_score: 71,
    apply_url: "https://careers.google.com/",
    match_reason: "Complete Phase 2 milestones to improve your match score for this role.",
  },
];

export const DEMO_SCHEDULE = [
  { day: "Monday", start: "09:00", end: "10:30", topic: "DSA Practice", color: "indigo" },
  { day: "Monday", start: "14:00", end: "15:00", topic: "HR Mock Interview", color: "cyan" },
  { day: "Tuesday", start: "10:00", end: "11:30", topic: "System Design Study", color: "indigo" },
  { day: "Tuesday", start: "16:00", end: "17:00", topic: "Project Work", color: "amber" },
  { day: "Wednesday", start: "09:00", end: "10:00", topic: "LeetCode Medium", color: "green" },
  { day: "Wednesday", start: "15:00", end: "16:30", topic: "Technical Interview", color: "indigo" },
  { day: "Thursday", start: "11:00", end: "12:00", topic: "Behavioural Prep", color: "cyan" },
  { day: "Thursday", start: "14:00", end: "15:30", topic: "DSA Practice", color: "green" },
  { day: "Friday", start: "09:00", end: "10:30", topic: "System Design", color: "indigo" },
  { day: "Friday", start: "16:00", end: "17:00", topic: "Mock Interview", color: "cyan" },
  { day: "Saturday", start: "10:00", end: "12:00", topic: "Project Work", color: "amber" },
  { day: "Saturday", start: "14:00", end: "15:00", topic: "LeetCode Hard", color: "green" },
];

export const DEMO_QUESTIONS = [
  {
    id: "q1",
    question: "Explain the difference between a stack and a queue. When would you use each?",
    domain: "Technical",
    difficulty: "Beginner",
  },
  {
    id: "q2",
    question: "How would you design a URL shortener like bit.ly? Walk me through the system architecture.",
    domain: "Technical",
    difficulty: "Intermediate",
  },
  {
    id: "q3",
    question: "Tell me about a time when you had to work with a difficult team member. How did you handle it?",
    domain: "HR",
    difficulty: "Intermediate",
  },
  {
    id: "q4",
    question: "What is the time complexity of searching in a balanced BST vs an unbalanced BST?",
    domain: "Technical",
    difficulty: "Beginner",
  },
  {
    id: "q5",
    question: "Design a notification system for a social media platform that handles millions of users.",
    domain: "Technical",
    difficulty: "Advanced",
  },
];

export const FEATURE_CARDS = [
  {
    icon: "Brain",
    title: "AI Mock Interviews",
    description: "Practice with AI-powered interviews that adapt to your skill level and career goals.",
  },
  {
    icon: "Target",
    title: "Career Roadmap",
    description: "Set your career objective and get a personalised month-by-month plan to get there.",
  },
  {
    icon: "BarChart3",
    title: "Performance Analytics",
    description: "Track your progress with detailed scorecards, radar charts, and AI-driven insights.",
  },
  {
    icon: "MessageSquare",
    title: "Sage AI Coach",
    description: "24/7 AI chatbot that knows your goals, progress, and weak areas. Always ready to help.",
  },
  {
    icon: "Shield",
    title: "Certificate Validator",
    description: "Upload certificates and let AI verify authenticity with OCR and metadata analysis.",
  },
  {
    icon: "Briefcase",
    title: "Internship Matching",
    description: "Get matched with internships based on your skills, goals, and roadmap progress.",
  },
];
